version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: library-db
    ports:
      - "10001:5432"
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
